_target_: ctrm.environment.instance.generate_ins_2d_with_obs_hetero_nonfix_agents
num_agents_min: 21
num_agents_max: 30
max_speeds_cands: "0.03125,0.0390625,0.046875"
rads_cands: "0.015625,0.01953125,0.0234375"
obs_num: 10
obs_size_lower_bound: 0.05
obs_size_upper_bound: 0.08
