defaults:
  - planner: pp

roadmap:
  _target_: ctrm.roadmap.get_timed_roadmaps_random_common
  T: 64
  num: ???
  wo_invalid_samples: true

seed: 46
rootdir: "/data/exp/"
insdir: ???

plot_2d_data: true
progress_bar_disable: false
max_eval_num: -1

hydra:
  run:
    dir: "${rootdir}/random_sampling/${now:%Y-%m-%d_%H-%M-%S}"
