defaults:
  - planner: pp

roadmap:
  _target_: ctrm.roadmap.get_timed_roadamaps_SPARS_2d
  T: 90
  sparse_delta_fraction: 0.1
  dense_delta_fraction: 0.01
  stretch_factor: 1.3
  time_limit_sec: 30.0

seed: 46
rootdir: "/data/exp/"
insdir: ???

plot_2d_data: true
progress_bar_disable: false
max_eval_num: -1
n_jobs: -1

hydra:
  run:
    dir: "${rootdir}/spars_sampling/${now:%Y-%m-%d_%H-%M-%S}"
