defaults:
  - planner: pp

roadmap:
  _target_: ctrm.roadmap.get_timed_roadmaps_grid
  T: 64
  size: ???

seed: 46
rootdir: "/data/exp/"
insdir: ???

plot_2d_data: true
progress_bar_disable: false
max_eval_num: -1

hydra:
  run:
    dir: "${rootdir}/grid_sampling/${now:%Y-%m-%d_%H-%M-%S}"
